- name: Download Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Start Prometheus
  ansible.builtin.systemd_service:
    state: restarted
    name: prometheus
    enabled: yes